content:
  - name: home
    label: Home Page
    type: file
    path: src/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: default.html }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }