content:
  - name: home
    label: Home Page
    type: file
    path: src/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: default.html }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: references
    label: References
    type: file
    path: src/references.md
    fields:
      - { name: layout, type: string, hidden: true, default: default.html }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: examples
    label: Examples
    type: collection
    path: src/examples
    filename: "{primary}.md"
    fields:
    - { name: title, label: Title, type: string }
    - { name: order, label: Order, type: number }
    - { name: body, label: Body, type: rich-text }
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
